name: weekly-fugle-charts


on:
schedule:
- cron: "0 1 * * 1" # 每週一 01:00 UTC（= 台北 09:00）
workflow_dispatch: # 允許手動觸發


jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
with:
python-version: '3.11'
- name: Install deps
run: |
python -m pip install --upgrade pip
pip install -r requirements.txt
- name: Generate charts
env:
FUGLE_API_KEY: ${{ secrets.FUGLE_API_KEY }}
run: python scripts/generate_charts.py
- name: Commit charts
run: |
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git add charts/* || echo "no new charts"
git commit -m "Weekly charts $(date -u +'%Y-%m-%d')" || echo "nothing to commit"
git push || echo "nothing to push"
